version: 3.8

services:
    postgres-krenolc:
        image: postgres:9.6.22-alpine
        container_name: postgres-krenolc
        ports:
            - 5432:5432
        networks: 
            - krenolc-network
    redis-krenolc:
        image: redis:6.2.3-alpine
        container_name: redis-krenolc
        ports: 
            - 6379:6379
        networks: 
            - krenolc-network
    krenolc-pizza:
        image: hrz8/krenolc-pizza:1.0
        container_name: krenolc-pizza
        ports:
            - 3009:3009
        depends_on: 
            - postgres-krenolc
            - redis-krenolc
        networks: 
            - krenolc-network

networks:
    krenolc-network:
        name: krenolc-network